name: 'DevCycle License Check'
description: 'Ensure that the repo uses licenses that comply with DevCycle standards'
inputs:
  language:
    description: 'The language of the project'
    required: true
    default: 'javascript'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      if: ${{ inputs.language == 'javascript' }}
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install license-checker
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: npm install -g license-checker
    - name: Check licenses
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: license-checker --json > licenses.json
    - name: Upload license report
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/upload-artifact@v2
      with:
        name: licenses
        path: licenses.json
    - name: Run Output
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: license-checker --exclude 'MIT, MIT OR X11, BSD, ISC, Apache-2.0, CC0-1.0, Unlicense, MPL-2.0, WTFPL, PSF, Python-2.0, Public Domain'