name: 'DevCycle License Check'
description: 'Ensure that the repo uses licenses that comply with DevCycle standards'
inputs:
  language:
    description: 'The language of the project'
    required: true
    default: 'javascript'
  package-manager:
    description: 'The package manager of the project'
    required: true
    default: 'yarn'
  safe-licenses-node:
    description: 'The list of safe licenses for node projects'
    required: true
    default: 'MIT, MIT OR X11, BSD, ISC, Apache-2.0, CC0-1.0, Unlicense, MPL-2.0, WTFPL, PSF, Python-2.0, Public Domain'
  unsafe-licenses-node:
    description: 'The list of unsafe licenses for node projects'
    required: true
    default: 'AGPL-3.0;GPL-3.0;GPL-2.0;GPL-1.0;LGPL-3.0;LGPL-2.1;LGPL-2.0;LGPL-2.0+;LGPL-2.1+;LGPL-3.0+;GPL-2.0+;GPL-3.0+;AGPL-3.0+;AGPL-3.0;AGPL-3.0+;LGPL-3.0-or-later'
  exclude-packages-node:
    description: 'List of packages to exclude from filtering; to allow mis-identified packages'
    required: true
    default: '@img/sharp-libvips-linux-x64@1.2.4;@img/sharp-libvips-linux-x64@1.2.0;@img/sharp-libvips-linux-x64@1.0.4'
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@v4
      if: ${{ inputs.language == 'javascript' }}
      with:
        node-version: 22
        cache: '${{ inputs.package-manager }}'

    - name: Install dependencies
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: ${{ inputs.package-manager }} install

    - name: Install license-checker
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: npm install -g license-checker

    - name: Check licenses
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: license-checker --exclude "${{ inputs.safe-licenses-node }}" --excludePackages "${{ inputs.exclude-packages-node }}" --json > licenses.json

    - name: Upload license report
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/upload-artifact@v4
      with:
        name: licenses
        path: licenses.json
        
    - name: Run Output
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: license-checker --exclude "${{ inputs.safe-licenses-node }}" --failOn "${{ inputs.unsafe-licenses-node }}" --excludePackages "${{ inputs.exclude-packages-node }}"
